name: coffee
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore:
  firebase_auth:
  firebase_core:
  firebase_storage:
  flutter:
    sdk: flutter
  google_sign_in:
  provider:
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
   - family: Jakarta
     fonts:
       - asset: assets/fonts/PlusJakartaSans-Bold.ttf
         weight: 700
       - asset: assets/fonts/PlusJakartaSans-Light.ttf
         weight: 300
       - asset: assets/fonts/PlusJakartaSans-Medium.ttf
         weight: 500
       - asset: assets/fonts/PlusJakartaSans-Regular.ttf
         weight: 400
       - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
         weight: 600